{"timestamp": "2025-05-19 09:37:29", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "SELECT security_level FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 449, in handle_client\n    user_action = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    request_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 09:45:57", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    request_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 09:47:08", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    request_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 09:48:14", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "SELECT security_level FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 449, in handle_client\n    user_action = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-19 10:49:10", "error_type": "OperationalError", "error_message": "near \"''\": syntax error", "query": "SELECT password FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 493, in login\n    curr.execute(query)\nsqlite3.OperationalError: near \"''\": syntax error\n"}
{"timestamp": "2025-05-19 10:49:32", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    request_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 10:49:59", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "SELECT password FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 485, in login\n    client_username = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-19 10:49:59", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 10:52:06", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "SELECT security_level FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 449, in handle_client\n    user_action = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    request_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-18 21:52:42", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:52:50", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:54:04", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:56:57", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:57:08", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:57:39", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:58:04", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:58:16", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:58:55", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "SELECT password FROM accounts WHERE username = 'hello'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 485, in login\n    client_username = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-18 21:58:55", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-17 07:00:31", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "SELECT password FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 485, in login\n    client_username = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-17 07:00:31", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-17 07:02:44", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "SELECT security_level FROM accounts WHERE username = 'johnny1'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 449, in handle_client\n    user_action = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-17 07:02:48", "error_type": "ConnectionResetError", "error_message": "Client disconnected unexpectedly", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Client disconnected unexpectedly\")\nConnectionResetError: Client disconnected unexpectedly\n"}
{"timestamp": "2025-05-19 11:12:40", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    response_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 11:14:31", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    response_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 11:15:40", "error_type": "ConnectionResetError", "error_message": "[WinError 10054] An existing connection was forcibly closed by the remote host", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 41, in receive_message\n    response_length_field = client_socket.recv(NUM_DIGITS_LENGTH_FIELD).decode()\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"}
{"timestamp": "2025-05-19 11:15:41", "error_type": "ValueError", "error_message": "invalid literal for int() with base 10: '91{\"msg\": '", "query": "NO QUERY", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 617, in client_entrance\n    login_or_signup = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 47, in receive_message\n    response_length = int(response_length_field)\nValueError: invalid literal for int() with base 10: '91{\"msg\": '\n"}
{"timestamp": "2025-05-19 11:16:47", "error_type": "ConnectionResetError", "error_message": "Server disconnected unexpectedly", "query": "SELECT security_level FROM accounts WHERE username = 'admin'", "source_ip": "127.0.0.1", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 449, in handle_client\n    user_action = receive_message(client_socket, client_aes_key)\n  File \"C:\\Users\\\u05de\u05d9\u05db\u05dc\\PycharmProjects\\pythonProject\\HoneypotProject\\SmallBusinessServer.py\", line 44, in receive_message\n    raise ConnectionResetError(\"Server disconnected unexpectedly\")\nConnectionResetError: Server disconnected unexpectedly\n"}
